---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

    I feel I have improved as a practitioner and student of data science by taking feedback in many forms and acting upon it. I have gained feedback in the form of grading by Dr. T, in reviews by my peers, and in the form of collaborating on Practice Activities in class. I feel to be a good data scientist, you have to not only be willing to receive feedback, but be receptive to it. One of the concepts we focused on this quarter was efficiency. I have received feedback in all three of the forms I mentioned on this concept, and feel that now at the end of the quarter, I have a good understanding of how to make my code more efficient. I feel I am more aware and write concise and efficient code with intention. Looking at my older labs, I am able to identify where my code is considered inefficient, and I have the knowledge on how to fix it.

    Another way I feel I have improved is by implementing skills that a good data scientist would. For example, a good data scientist would produce tables and plots that have the necessary details, as well as some additional details that would provide some extra context or aid in understanding. As the quarter went on, I developed those skills and used them to produce output that was clear, had descriptive labels, and arranged in a way so that the reader would not have to tilt their head.

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

    One area of growth for me was making my plots visually appealing and viewer friendly. I started out the quarter not really taking into consideration the colors used and where my labels were and what they looked like. In my portfolio, I used the code chunk from Lab 9 Question 8 to showcase a plot I was happy with, and I feel it aligns with this area of growth. I used labels that were descriptive and freed the y axis. I used a facet_wrap so that I could show the different sample sizes clearly. I included a vertical line to show the mean on the plot for comparability and used a contrasting color so that is was obvious.

    Another area of growth for me was being more creative. At the beginning of the quarter I was making basic plots and tables and not really trying the spicier or more challenging questions. As the quarter went on, I started getting more comfortable with my understanding of the basic plot and table code and started pushing myself more. In my portfolio, I used the code chunk from Lab 9 Question 2 as evidence that I can show creativity in tables, and I think it is a good reflection of my growth. I used gt() to help format my table nicely and converted my proportions to percentages. Another example of my growth on this subject in the portfolio is from Lab 9 Question 7. I used the kable function with html formatting and made the names of my columns descriptive and clear.
